$schema: https://json-schema.org/draft-07/schema
$defs:
  Accounts:
    additionalProperties: false
    description: InNoHassle Accounts integration settings
    properties:
      api_url:
        default: https://api.innohassle.ru/accounts/v0/
        description: URL of the Accounts API
        title: Api Url
        type: string
      api_jwt_token:
        description: JWT token for accessing the Accounts API as a service
        format: password
        title: Api Jwt Token
        type: string
        writeOnly: true
    required:
    - api_jwt_token
    title: Accounts
    type: object
  Booking:
    additionalProperties: false
    description: Booking API integration settings
    properties:
      api_url:
        default: https://api.innohassle.ru/room-booking/staging-v0/
        description: URL of the Booking API
        title: Api Url
        type: string
    title: Booking
    type: object
  CoreCoursesConfig:
    description: Config for electives parser from Google Sheets
    properties:
      targets:
        items:
          $ref: '#/$defs/Target'
        title: Targets
        type: array
    required:
    - targets
    title: CoreCoursesConfig
    type: object
  Target:
    description: Target model
    properties:
      sheet_name:
        title: Sheet Name
        type: string
      start_date:
        format: date
        title: Start Date
        type: string
      end_date:
        format: date
        title: End Date
        type: string
    required:
    - sheet_name
    - start_date
    - end_date
    title: Target
    type: object
  TeacherDTO:
    additionalProperties: false
    properties:
      name:
        description: First and second name of teacher
        title: Name
        type: string
      group:
        description: Group of a teacher
        title: Group
        type: string
      email:
        description: Email of teacher
        title: Email
        type: string
    required:
    - name
    - group
    - email
    title: TeacherDTO
    type: object
additionalProperties: false
description: Settings for the application.
properties:
  $schema:
    default: null
    title: $Schema
    type: string
  app_root_path:
    default: ''
    description: Prefix for the API path (e.g. "/api/v0")
    title: App Root Path
    type: string
  cors_allow_origin_regex:
    default: .*
    description: 'Allowed origins for CORS: from which domains requests to the API
      are allowed. Specify as a regex: `https://.*.innohassle.ru`'
    title: Cors Allow Origin Regex
    type: string
  accounts:
    $ref: '#/$defs/Accounts'
  booking:
    $ref: '#/$defs/Booking'
    default:
      api_url: https://api.innohassle.ru/room-booking/staging-v0/
  teachers:
    description: List of teachers
    items:
      $ref: '#/$defs/TeacherDTO'
    title: Teachers
    type: array
  core_courses_config:
    $ref: '#/$defs/CoreCoursesConfig'
    description: Config for core courses parser from Google Sheets
required:
- accounts
- teachers
- core_courses_config
title: Settings
type: object
