# yaml-language-server: $schema=settings.schema.yaml
$schema: "./settings.schema.yaml"
# ---------- Application settings ----- #

accounts:
  # Get from https://api.innohassle.ru/accounts/v0/tokens/generate-service-token?sub=room-booking-local-dev&scopes=users&only_for_me=true
  api_jwt_token: "token"

teachers: []

core_courses_config:
  targets:
    - sheet_name: "Ru Programs"
      start_date: "2025-06-02"
      end_date: "2026-07-21"

    - sheet_name: "1st block common"
      start_date: "2025-06-02"
      end_date: "2026-07-21"
